### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by ghost** [ctorney/Daily-Diary#4]
Hello, just saw your app on Reddit and wanted to contribute with a Spanish translation. It's my first time using GitHub so I don't know what's the right way to go about this, all I could come up with is attaching the translated strings.xml file as a .txt here. Sorry for the trouble, and thank you for your app.
[strings.txt](https://github.com/ctorney/Daily-Diary/files/10888977/strings.txt)

**Comment by ctorney** [comment]
thanks - now added so it'll appear in the next build. I'll wait a few days before putting out another prerelease in case anyone else wants to add a translation
